# action.yml
name: 'Add Reviewer'
description: 'Add reviewer to GitHub pull request'
inputs:
  username:
    description: 'GitHub username'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}